### ISSUE TITLE
Dyn DNS para Arduino

### ISSUE THREAD

**Issue by controlacceso** [controlacceso/control_acceso#3]
https://github.com/DFRobot/arduino-projects/blob/master/libraries/DDNS/example/example.ino

**Comment by zmwebdev** [comment]
https://www.arduino.cc/en/Reference/Libraries

https://www.arduino.cc/en/Reference/Ethernet

https://www.arduino.cc/en/Reference/GSM

https://www.arduino.cc/en/Reference/WiFi

**Comment by zmwebdev** [comment]
http://mqtt.org/

https://systembash.com/mqtt-vs-websockets-vs-http2-the-best-iot-messaging-protocol/

**Comment by natiexperiencia** [comment]
MQTT
