### ISSUE TITLE
Mongolabs login error

### ISSUE THREAD

**Issue by natiexperiencia** [controlacceso/control_acceso#314]
Lortu det...
Mongolabs eguneratu egin dute 3.0 bertsiora eta ScramSHA1 encriptazio sistema erabiltzen dute...
Konexioan aipatu egin behar da:
mongoose.connect('mongodb://'+user+':'+password+'@ds059215.mongolab.com:59215/faltas',{authMechanism: 'ScramSHA1'});

@zmwebdev

**Comment by zmwebdev** [comment]
Oso ondo!
Nere kodea eguneratuko dut.
